### ISSUE TITLE
Unable to switch to VR mode using Ctrl + Tab keys in MSFS2020 using PimaxXR v0.4.0 on 8KX

### ISSUE THREAD

**Issue by Evovita** [mbucchia/Pimax-OpenXR#60]
**Describe the bug**

Unable to switch to VR mode using `Ctrl + Tab` keys in _MSFS2020_. Pressing the keys does not turn on VR in my _Pimax 8KX_ headset.

**Environment**

- _PimaxXR_ v0.4.0
- _PiTool_ v1.0.1.277
- _Pimax 8KX_ with Firmware v2.1.255.299
- _MSFS2020_ v1.33.8.0

**PimaxXR runtime settings (as per default on install)**

![image](https://github.com/mbucchia/Pimax-OpenXR/assets/9646354/c41b1131-deef-4f3f-b8f7-c6b06ffce074)

**To Reproduce**

1. Start _PiTool_ .
2. Start headset.
3. Start _PimaxXR_, ensure set to `PimaxXR` mode
4. Run _MSFS2020_ from _PiTool_ Game list.
5. Create a new flight, and wait for it to load.
6. Press `Ctrl + Tab` keys.

**Expected behavior**

_MSFS2020_ switches to VR mode and I can see the image in the headset.

**Log file**

[pimax-openxr.log](https://github.com/mbucchia/Pimax-OpenXR/files/11932730/pimax-openxr.log)

**Workaround**

Uninstall _PimaxXR_ v0.4.0, then install _PimaxXR_ v0.3.4 - `Ctrl + Tab` keys work as expected and can use headset.

**Comment by mbucchia** [comment]
Based on the log file you are just seeing a transient bug from Pitool. A reboot should fix it.

Also this version of Pitool is largely outdated, you are something like 9 versions behind... please upgrade.

**Comment by Evovita** [comment]
> Based on the log file you are just seeing a transient bug from Pitool. A reboot should fix it.
> 
> Also this version of Pitool is largely outdated, you are something like 9 versions behind... please upgrade.

Thanks for your fast response. PC restart did not resolve the issue.

`Check Version` in _PiTool_ states I already have the latest version. At [Pimax download site](https://pimax.com/downloads-manuals/) a newer version doesn't exist, and I can't find anything else on their web site to suggest a newer version is available. I found [this link](https://sh-dcc.oss-accelerate.aliyuncs.com/dcc/pitool/PiToolSetup_toC_1.0.1.283.exe) but it's not a Pimax domain link so I'm not going to risk running it.

![image](https://github.com/mbucchia/Pimax-OpenXR/assets/9646354/5fe7738c-ef3f-4a5d-a504-63a0e36b5f45)

**Comment by mbucchia** [comment]
If that did not solve the issue then it just means 0.4.0 isn't compatible. **But again your pitool is over a year old.**

The check for update feature is broken.

Pimax is really bad at publishing official updates 
You can see here their announcement for the new release of Pimax Client.


https://www.reddit.com/r/Pimax/comments/14az2e7/pimax_client_v112/

**Comment by Evovita** [comment]
> If that did not solve the issue then it just means 0.4.0 isn't compatible. **But again your pitool is over a year old.**
> 
> The check for update feature is broken.
> 
> Pimax is really bad at publishing official updates You can see here their announcement for the new release of Pimax Client.
> 
> https://www.reddit.com/r/Pimax/comments/14az2e7/pimax_client_v112/

I found [this link for Pimax Client versions](https://community.openmr.com/c/pi-soft/41) - once I realized _Pimax Client_ replaces installing _PiTool_ directly.

After installing _Pimax Client_ inc. upgrading it to v1.13.00.01, the `Ctrl + Tab` keys in MSFS2020 now work to switch to VR.

Thank you for your help! 👍

**Comment by mbucchia** [comment]
It's a little confusing yes. Glad it's working now.
